# 📘 NumPy 2D-3D array


🎯 Hva er en 3D Array?
En 3D array er som flere 2D arrays (matriser) stablet oppå hverandre!
Tenk på det som:

📚 En bok med flere sider
🎨 Flere ark med papir stablet
🧊 En terning med tall

📊 Diagram 1: Hvordan lage en 3D array


In [ ]:
# Code example / demonstration


📊 Diagram 1: Hvordan lage en 3D array
|

In [29]:
arr_3D = np.array([
    [[1, 2], [3, 5]], # "Layer" 0 (første side)
    [[5,6], [7, 8]]    
])



🎲 Diagram 2: Lage 3D arrays med funksjoner

In [ ]:
np.ones((4, 3, 2))


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

🔢 3D Array Shape forklaring:

shape = (layers, rows, columns)
shape = (dybde, høyde, bredde)
shape = (z, y, x)
```

### Eksempler:

#### `np.ones((4, 3, 2))`:
```
4 layers (4 "bøker")
3 rows per layer (3 linjer per side)
2 columns per row (2 tall per linje)

Total elementer: 4 × 3 × 2 = 24 elementer
```

#### `np.zeros((4, 3, 2))`:
```
Samme structure, men fylt med 0 i stedet for 1
```

#### `np.random.random((4, 3, 2))`:
```
Samme structure, men fylt med tilfeldige tall (0 til 1)

📝 Kodeeksempel:

In [33]:
import numpy as np

# Lag en 3D array med ones
arr= np.ones((4, 3, 2))

print(f"shape: {arr.shape}")
print(f"Dimensions: {arr.ndim}")
print(f"Size: {arr.size}")

# Print hele arrayen
print(arr)

shape: (4, 3, 2)
Dimensions: 3
Size: 24
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


🎯 Indexing i 3D arrays:

In [46]:
arr_3d = np.array([
    [[1, 2], [3, 4]],    # Layer 0
    [[5, 6], [7, 8]]     # Layer 1
])

# Syntaks: arr[layer, row, column]

# Hent ett element:
print(arr_3d[0, 0, 0])  # 1 (layer 0, rad 0, kolonne 0)
print(arr_3d[0, 0, 1])  # 2 (layer 0, rad 0, kolonne 1)
print(arr_3d[1, 1, 1])  # 8 (layer 1, rad 1, kolonne 1)

# Hent en hel layer:
print(arr_3d[0])
# [[1 2]
#  [3 4]]

# Hent en rad fra en layer:
print(arr_3d[0, 0])     # [1 2] (layer 0, rad 0)

# Hent en kolonne fra alle layers:
print("en kilonne fra alle layers:", arr_3d[:, 0, 0])


1
2
8
[[1 2]
 [3 4]]
[1 2]
en kilonne fra alle layers: [1 5]


In [48]:
# Et 100x100 RGB-bilde er en 3D array:
image = np.random.randint(0, 255, size=(100, 100, 3))
#                                       ↑    ↑   ↑
#                                       │    │   └─ 3 fargekanaler (R, G, B)
#                                       │    └───── 100 rader (høyde)
#                                       └────────── 100 kolonner (bredde)

# Layer 0 = Rød kanal
# Layer 1 = Grønn kanal  
# Layer 2 = Blå kanal

print(image)

[[[ 16  94  28]
  [114 227   7]
  [  9  53  18]
  ...
  [ 59  65  95]
  [ 19 108 114]
  [ 11 122 181]]

 [[ 67 145 180]
  [154 125 156]
  [  1 212  79]
  ...
  [ 97  73  43]
  [252  96  17]
  [ 60 243  14]]

 [[213 238  14]
  [235 101 136]
  [  2 137 221]
  ...
  [ 20 120 138]
  [235 237  55]
  [231  45 246]]

 ...

 [[ 45  22  48]
  [122 148  94]
  [121 189  10]
  ...
  [183  68 252]
  [175  46  33]
  [ 88  68 177]]

 [[201  51  89]
  [ 51 241 148]
  [114 174 166]
  ...
  [168 224 195]
  [ 67  74 246]
  [199 252 129]]

 [[ 50 203  40]
  [ 32  81  89]
  [ 21 186  24]
  ...
  [103  59  90]
  [162 231 222]
  [247 141 173]]]


## 📝 Key Takeaways
- 
- 


## ❓ Questions / Topics to Review
- 
- 
