# NumPy 1D Arrays - Viktigste Konsepter


## Objectives

After completing this notebook you will be able to:

*   Import and use the `numpy` library
*   Perform operations with `numpy`



1️⃣ Hva er forskjellen: Python List vs NumPy Array?

Python List:

In [1]:
# Python list - kan inneholde Forkjellige datatyper
python_list = ["0", 1, "two", "3", 4] # String, int, string, string, int
print(python_list)
print(type(python_list)) # <class 'list'>


['0', 1, 'two', '3', 4]
<class 'list'>


Egenskaper:

✅ Fleksibel - kan inneholde strings, tall, booleans blandet
❌ Treg for matematiske operasjoner
❌ Må bruke loops for å endre alle elementer

NumPy Array:


In [5]:
import numpy as np

# NumPy array - inneholder samme datatype
numpy_array = np.array([0, 1, 2, 3, 4]) # Alle elementer er int
print(numpy_array)
print(type(numpy_array)) # <class 'numpy.ndarray'>
print(numpy_array.dtype) # Viser datatype (int64, float64, etc.)




[0 1 2 3 4]
<class 'numpy.ndarray'>
int64


Egenskaper:

✅ Rask for matematiske operasjoner

✅ Vectorized operations (operasjoner på hele arrayen samtidig)

✅ Bruker mindre minne

⚠️ Alle elementer må være samme datatype

2️⃣ Lage NumPy Arrays - Forskjellige metoder




A) Fra Python List:

In [6]:
import numpy as np

# Fra vanlig list
a = np.array([1, 2, 3, 4, 5])
print(a)


[1 2 3 4 5]



B) Med np.arange() (som Python's range()):

In [9]:
# np.arange(start, stop, step)
# OBS: stop er IKKE inkludert (akkurat som range)

a = np.arange(0, 10, 1) # 0, 1, 2, ..., 9
print(a)

b = np.arange(0, 10, 2) # 0, 2, 4, 6, 8 (partall)
print(b)

c = np.arange(1, 10, 2) # 1, 3, 5, 7, 9 (oddall)
print(c)

d = np.arange(10) # 0, 1, 2, ..., 9 (kortform)
print(d)



[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[0 1 2 3 4 5 6 7 8 9]


C) Med np.linspace() (lineært mellomrom):

In [11]:
# np.linspace(start, stop, num)
# OBS: stop ER inkludert! (forskjell fra arange)

a = np.linspace(0, 10, 5) # 5 tall fra 0 til 10 (inkludert 10)
print(a) # [0. 2.5 7.5 10.]

b = np.linspace(0, 1, 11) # 11 tall fra 0 til 1
print(b)    




[ 0.   2.5  5.   7.5 10. ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


Når bruker du hvilken?

arange: Når du vil ha heltall med bestemt steg
linspace: Når du vil ha et bestemt ANTALL tall mellom to verdier

D) Spesielle arrays:

In [ ]:
# Array med bare nuller
zeros = np.zeros(5) #[0. 0. 0. 0. 0.]

# Array med bare enere
ones = np.ones(5) # [1. 1. 1. 1. 1.]

# Array med tilfeldige tall
random = np.random.rand(5) # 5 tilfeldige tall mellom 0 og 1




3️⃣ Indexing - Hente ut elementer

NumPy array indexing fungerer akkurat som Python lists:

In [16]:
a = np.array([10, 20, 30, 40, 50])
#             0    1   2    3    4  <- Indekser
#            -5   -4  -3   -2   -1  <- negative indekser

# Hente enkelt element:
print(a[0])    # 10 (første element)
print(a[2])    # 30 (tredje element)
print(a[-1])   # 50 (siste element)
print(a[-2])   # 40 (nest siste element)


# Endre elemnt:
a[0] = 100
print(a)




10
30
50
40
[100  20  30  40  50]


4️⃣ Slicing - Hente ut deler av array


Syntaks: array[start:stop:step]

In [18]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Grunnleggende slicing:
print(a[2:5])      # [2, 3, 4] (fra index 2 til 5, ikke inkludert 5)
print(a[:5])       # [0, 1, 2, 3, 4] (fra start til 5)
print(a[5:])       # [5, 6, 7, 8, 9] (fra 5 til slutt)
print(a[:])        # Hele arrayen (kopi)

# Med step:
print(a[::2])      # [0, 2, 4, 6, 8] (hvert andre element)
print(a[1::2])     # [1, 3, 5, 7, 9] (oddetall - start på index 1)
print(a[::3])      # [0, 3, 6, 9] (hvert tredje element)

# Reversere array:
print(a[::-1])     # [9, 8, 7, 6, 5, 4, 3, 2, 1, 0] (baklengs)

# Komplekse eksempler:
print(a[2:8:2])    # [2, 4, 6] (fra 2 til 8, hvert andre)
print(a[-5:-1])    # [5, 6, 7, 8] (siste 5 til nest siste)

[2 3 4]
[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[1 3 5 7 9]
[0 3 6 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6]
[5 6 7 8]


Viktig å huske:

start er inkludert

stop er IKKE inkludert

step er hvor mange du hopper

5️⃣ Array Attributes - Egenskaper

In [19]:
a = np.array([1, 2, 3, 4, 5])

# Datatype:
print(a.dtype)   # int64 (eller int32 avhengig av system)

# Størrelse (antall elementer):
print(a.size)    # 5

# Dimensjon (1D, 2D, 3D, etc):
print(a.ndim)          # 1 (en-dimensjonal)

# Shape (form/dimensjoner):
print(a.shape)         # (5,) - betyr 1D array med 5 elementer

int64
5
1
(5,)


6️⃣ Vectorized Operations - Matematikk på hele arrays



Dette er superkraften til NumPy! 🦸‍♂️

Aritmetikk med scalar (ett tall):

In [ ]:
a = np.array([1, 2, 3, 4, 5,])

# Alle elementer + 10:
print(a + 10)   #[11, 12, 13, 14, 15]

# Alle elementer * 2:
print(a * 2)    # [2, 4, 6, 8, 10]

# Alle elementer **2 (kvadrert):
print(a ** 2)      # [1, 4, 9, 16, 25]

# Alle elementer / 2:
print(a / 2)      #[0.5, 1., 1.5, 2., 2.5]

[11 12 13 14 15]
[ 2  4  6  8 10]
[ 1  4  9 16 25]
[0.5 1.  1.5 2.  2.5]


Aritmetikk mellom to arrays (element-wise):


In [21]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

# Legg sammen element for element:
print(a + b)      # [11, 22, 33, 44, 55]

# Multipliser element for element:
print(a * b)      # [10, 40, 90, 160, 250]

# Trekk fra:
print(b - a)      # [9, 18, 27, 36, 45]

[11 22 33 44 55]
[ 10  40  90 160 250]
[ 9 18 27 36 45]


Matematiske funksjoner:

In [22]:
a = np.array([1, 2, 3, 4, 5])

# Statistikk
print(a.mean())        # 3.0 (gjennomsnitt)
print(a.sum())         # 15 (sum)
print(a.std())         # 1.414... (standardavvik)
print(a.min())         # 1 (minimum)
print(a.max())         # 5 (maximum)


# Finn index til min/max
print(a.argmin())    # 0 (index til minimum)
print(a.argmax())    # 4 (index til maximum)


# Matematikk funksjoner:
print(np.sqrt(a))    # [1. 1.414 1.732 .2 2.2386] (kvadratrot)
print(np.sin(a))      # [0.841 0.909 0.141 -0.757 -0.959] (sinus)
print(np.exp(a))      # [2.718 7.389 20.086 54.598 148.413] (e^x)
print(np.log(a))      # [0. 0.693 1.099 1.386 1.609] (naturlig log)


3.0
15
1.4142135623730951
1
5
0
4
[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


7️⃣ Universal Functions (ufuncs)


NumPy har mange innebygde funksjoner som jobber element-wise:

In [23]:
a = np.array([1, 4, 9, 16, 25])

# Matematikk:
print(np.sqrt(a))      # [1. 2. 3. 4. 5.]
print(np.square(a))    # [1, 16, 81, 256, 625]
print(np.abs(a))       # Absolutt verdi

# Trigonometri:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))  # [0. 1. 0.]
print(np.cos(angles))  # [1. 0. -1.]

# Avrunding:
b = np.array([1.2, 2.7, 3.5, 4.1])
print(np.round(b))     # [1. 3. 4. 4.]
print(np.floor(b))     # [1. 2. 3. 4.] (rund ned)
print(np.ceil(b))      # [2. 3. 4. 5.] (rund opp)

[1. 2. 3. 4. 5.]
[  1  16  81 256 625]
[ 1  4  9 16 25]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[1. 3. 4. 4.]
[1. 2. 3. 4.]
[2. 3. 4. 5.]


8️⃣ Boolean Indexing - Filtrering


In [ ]:
Du kan bruke betingelser til å filtrere arrays! 🎯

In [24]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Lag en boolean mask:
mask = a > 5
print(mask)  # [False False False False False True True True True True]

# Bruk masken til å filtrere:
result = a[mask]
print(result)  # [6, 7, 8, 9, 10]

# Eller direkte:
print(a[a > 5])      # [6, 7, 8, 9, 10]
print(a[a % 2 == 0]) # [2, 4, 6, 8, 10] (partall)
print(a[a % 2 != 0]) # [1, 3, 5, 7, 9] (oddetall)

# Kombinere betingelser:
print(a[(a > 3) & (a < 8)])  # [4, 5, 6, 7] (AND - begge må være true)
print(a[(a < 3) | (a > 8)])  # [1, 2, 9, 10] (OR - en av dem må være true)

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]
[4 5 6 7]
[ 1  2  9 10]


9️⃣ Array Copying - Deep vs Shallow Copy


VIKTIG KONSEPT! ⚠️

In [25]:
a = np.array([1, 2, 3, 4, 5])

# 1. Assignment (= ) - IKKE en kopi!
b = a
b[0] = 999
print(a)  # [999, 2, 3, 4, 5] <- a ble også endret! 😱
print(b)  # [999, 2, 3, 4, 5]

# 2. View (shallow copy) - Deler data
a = np.array([1, 2, 3, 4, 5])
c = a.view()
c[0] = 888
print(a)  # [888, 2, 3, 4, 5] <- a ble også endret!
print(c)  # [888, 2, 3, 4, 5]

# 3. Copy (deep copy) - Selvstendig kopi ✅
a = np.array([1, 2, 3, 4, 5])
d = a.copy()
d[0] = 777
print(a)  # [1, 2, 3, 4, 5] <- a er uendret! 👍
print(d)  # [777, 2, 3, 4, 5]

[999   2   3   4   5]
[999   2   3   4   5]
[888   2   3   4   5]
[888   2   3   4   5]
[1 2 3 4 5]
[777   2   3   4   5]


Huskeregel: Bruk alltid .copy() hvis du vil ha en selvstendig kopi!

🔟 Sammenligning: List Comprehension vs Vectorization

In [26]:
import numpy as np
import time

# Lag store datasett
size = 1000000
python_list = list(range(size))
numpy_array = np.array(range(size))

# Python list - må bruke loop
start = time.time()
doubled_list = [x * 2 for x in python_list]
python_time = time.time() - start

# NumPy - vectorized
start = time.time()
doubled_array = numpy_array * 2
numpy_time = time.time() - start

print(f"Python list: {python_time:.4f} sek")
print(f"NumPy array: {numpy_time:.4f} sek")
print(f"NumPy er {python_time/numpy_time:.1f}x raskere!")

Python list: 0.0638 sek
NumPy array: 0.0033 sek
NumPy er 19.1x raskere!


# 📝 Oppsummering - Viktigste Takeaways

Husk disse:

Import NumPy: import numpy as np
Lage arrays:

np.array([1,2,3])
np.arange(start, stop, step)
np.linspace(start, stop, num)


Indexing: a[0], a[-1]
Slicing: a[start:stop:step]
Vectorized operations: a * 2, a + 10, a ** 2
Statistikk: .mean(), .sum(), .std(), .min(), .max()
Boolean indexing: a[a > 5]
Kopier: Bruk .copy() for selvstendig kopi